
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

pod 'PNChartSwift',:git => 'https://github.com/kevinzhow/PNChart-Swift.git'

target 'DemoPNChartSwift' do

end

target 'DemoPNChartSwiftTests' do

end
