# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

pod 'GPUImage'

target 'DemoSwift3.0' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoSwift3.0

  target 'DemoSwift3.0Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
