# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoSwiftRN' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoSwiftRN
  pod 'React', :path => './node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
  ]

  target 'DemoSwiftRNTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
