# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'PKHUD'
pod 'MBProgressHUD'

target 'DemoPKHUD' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoPKHUD

end
