# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'DemoMaterial' do

pod 'Material'

end

target 'DemoMaterialTests' do

end

target 'DemoMaterialUITests' do

end

use_frameworks!
